Disable sentry's default integrations when using it
symfony/MonologBundle pull request #316
Opened 2019-08-14 16:21 UTC by Taluu

Monolog already does it, as the request integration that comes with the default configuration of sentry.

Disabling it fixes it. Maybe we should add a marker that says we could activate it ? I doubt the interest but I could be wrong.

poke @B-Galati

2019-08-14 17:39 UTC, B-Galati approved these changes
Great!

2019-08-14 20:50 UTC, B-Galati commented
In fact it would be good to keep Request Integration enabled as it gives a lot of useful information.

2019-08-14 21:01 UTC, Taluu commented
Thought about it, but as there's already the request processor on monolog, didn't think it'd be useful : https://github.com/Seldaek/monolog/blob/master/src/Monolog/Processor/WebProcessor.php

2019-08-14 21:18 UTC, B-Galati commented
That processor is cool but I think it is doing less than Sentry Request Integration.
Also, the goal of the processor is to add information on every single log while Request Integration will add these informations on each captured event which makes more sense for a tool like Sentry where log context is less readable.
Last thing, it's possible that the SentryHandler will not support the "extra" key from log context in future releases. Should be major one but still interesting to know.

2019-08-19 15:41 UTC, Taluu commented
> Last thing, it's possible that the SentryHandler will not support the "extra" key from log context in future releases. 

Source ?

Anyway, I managed to readd the request integration. poke @B-Galati @lyrixx

2019-08-20 05:53 UTC, B-Galati commented
> > Last thing, it's possible that the SentryHandler will not support the "extra" key from log context in future releases.
> 
> Source ?

https://github.com/getsentry/sentry-python/pull/457#issuecomment-519591414 -> that links to a comment in sentry-php.

2019-08-20 06:02 UTC, B-Galati commented
IMHO it would simpler to manage with a factory class that handles all cases.

Like this one: https://github.com/B-Galati/monolog-sentry-handler/blob/master/doc/guide-symfony.md#step-1-configure-sentry-hub

2019-08-20 06:04 UTC, B-Galati commented
Also, It is needed to set the global Hub by calling `Hub::setCurrent()`:

```php
// A global HubInterface must be set otherwise some feature provided by the SDK does not work as they rely on this global state
Hub::setCurrent(new Hub($client));
```

2019-08-20 13:57 UTC, lyrixx approved these changes
:+1: LGTM.

2019-08-20 14:26 UTC, lyrixx requested changes
Do not merge, this is not ready yet.

2019-09-02 21:02 UTC, inverse commented
@Taluu needs to be rebased from master due to short array clean up :+1:

2019-09-03 07:55 UTC, Taluu commented
Done. I'll try to find a way to set the global hub state, even though it's repulsive (through a factory or a configurator, probably)

2021-03-15 07:57 UTC, jderusse commented
Hello what is the status of this PR? why @lyrixx asked for not merging it?

2021-03-15 10:29 UTC, Taluu commented
IIRC, it was because sentry relies on a global state, preventing from really having multiple handlers. I can't remember having made any progress, but I think maybe they had some on their side.

We will need to check with sentry's sdk.

2021-03-15 13:07 UTC, lyrixx commented
Unfortunately, I can not remember. Sorry.
BTW, je sentry handler that is integrated with monolog is really far from perfect.

In my application, I end up with a full rewrite + a basic "service" handler

2021-03-15 16:01 UTC, B-Galati commented
And since then they introduced a new major version.

2025-10-17 15:43 UTC, HypeMC commented
Since support for the Sentry type has been deprecated in #537 should we close this one? cc @GromNaN

2025-10-17 15:46 UTC, GromNaN commented
Yes.

2025-10-17 15:46 UTC, closed without merging