Add enabled parameter in configuration
symfony/MonologBundle pull request #482
Opened 2024-05-27 13:01 UTC by Arkalo2

This feature aims to separate the enabling of handlers based on the environment.

## Use Case :

You have 3 servers on your project : dev, staging, and prod
- On your **dev** machine, you are in the **dev** environment.
- On your **staging** server, you are in the **prod** environment.
- On your **prod** server, you are in the **prod** environment.

Currently, you can't disable handlers for a specific environment. For an instance, you can't disable logging only in your staging environment.

With the enabled parameter, you are able to disable logging only in the staging environment.

2025-06-16 12:40 UTC, nicolas-grekas commented on DependencyInjection/Configuration.php
> +                ->scalarNode('enabled')->defaultTrue()->end()
is it intended that this is not a booleanNode?

2025-06-16 12:40 UTC, nicolas-grekas commented on DependencyInjection/MonologExtension.php
> +                if(false === $handler['enabled']) {
CS is borken
and if this is a boolean, there's no need for any comparisons:
```suggestion
                if (!$handler['enabled']) {
```

2025-09-26 08:17 UTC, GromNaN requested changes
I find this feature useful. Could you like to rebase your PR on the branch 3.x (we moved files), and add a test case in [FixtureMonologExtensionTestCase](https://github.com/symfony/monolog-bundle/blob/3.x/tests/DependencyInjection/FixtureMonologExtensionTestCase.php)?

2025-09-26 08:17 UTC, GromNaN commented on DependencyInjection/Configuration.php
> +                ->scalarNode('enabled')->defaultTrue()->end()
Indeed, a `booleanNode` should be used here because this value is used during compilation and cannot accept an environment variable.

2025-10-15 15:02 UTC, GromNaN commented on tests/DependencyInjection/Compiler/LoggerChannelPassTest.php
> +        $this->assertTrue($container->hasDefinition('monolog.handler.main'));
As the tests are almost identical, we can merge them by passing a boolean with a testWith annotation. That way we ensure there is no other reason that make definition non-existing.
```php
    /**
     * @testWith [true]
     *           [false]
     */
    public function testEnabledHandler($enabled): void
    {
        // ['enabled' => $enabled];

        $this->assertSame($enabled, $container->hasDefinition('monolog.handler.main'));
    }
```

2025-10-15 16:44 UTC, Arkalo2 commented on tests/DependencyInjection/Compiler/LoggerChannelPassTest.php
> +        $this->assertTrue($container->hasDefinition('monolog.handler.main'));
Cool ! I did not know

2025-10-15 21:00 UTC, GromNaN commented on tests/DependencyInjection/Compiler/LoggerChannelPassTest.php
> +    public function testDisabledHandler()
Then this test is a duplicate of the previous one with false

2025-10-16 07:25 UTC, GromNaN approved these changes

2025-10-16 11:28 UTC, GromNaN commented
Thank you @Arkalo2.

2025-10-16 11:28 UTC, merged

2025-10-16 12:13 UTC, Arkalo2 commented
Thanks @GromNaN @nicolas-grekas for your reviews

I'll add a PR for documentation